import SneakEase from "../assets/images/projects/sneakEase.png";
import ToursAndTravels from "../assets/images/projects/toursandtravels.png";
import Netflix from "../assets/images/projects/netflix.png";
import ChatApp from "../assets/images/projects/chatApp.png";

export const projects = [
  {
    id: 1,
    title: "Chat And Call App",
    date: "",
    description:
      "Real time chat, audio and video call app. Developed using socket.io and other advanced libraries. Also used multi social media login. Daisyui is used for styling.",
    image: ChatApp,
    tags: [
      "TypeScript",
      "React Js",
      "Node Js",
      "Express Js",
      "MongoDB",
      "Mongoose",
      "Socket.io",
      "Redux",
      "DaisyUI",
      "Passport Js",
      "Formik",
      "Redis",
      "Yup",
      "Joi",
      "NodeMailer",
      "Winston",
      "Cloudinary",
      "MediaRecorderAPI",
      "...",
    ],
    category: "web app",
    github: "https://github.com/AnirudhPV123/ChatApp",
  },
  {
    id: 2,
    title: "Tours And Travels",
    date: "",
    description:
      "Developed a comprehensive tours and travel website using MERN stack (MongoDB, Express.js, React.js, Node.js) to provide users with an immersive and interactive experience.",
    image: ToursAndTravels,
    tags: [
      "Javascript",
      "React Js",
      "Node Js",
      "Express Js",
      "MongoDB",
      "Razorpay",
      "JWT",
      "Base64",
      "...",
    ],
    category: "web app",
    github: "https://github.com/AnirudhPV123/Tours-and-Travels-1",
    webapp: "https://kvatravels.netlify.app",
  },
  {
    id: 3,
    title: "SneakEase[Ongoing]",
    date: "",
    description:
      "Leading development of SneakEase, an e-commerce platform for shoes. Designed an engaging frontend using Figma, focusing on dynamic navigation and user experience.",
    image: SneakEase,
    tags: [
      "TypeScript",
      "Next Js",
      "Node Js",
      "Express Js",
      "MongoDB",
      "Mongoose",
      "Redux",
      "Passport Js",
      "Shadcn",
      "Passport Js",
      "Formik",
      "Redis",
      "Yup",
      "Joi",
      "NodeMailer",
      "Winston",
      "Cloudinary",
      "Figma",
      "...",
    ],
    category: "web app",
    github: "https://github.com/AnirudhPV123/SneakEase",
  },
  {
    id: 9,
    title: "Netflix(Homepage Clone)",
    date: "",
    description: "Developed Netflix homepage using react and popular APIs",
    image: Netflix,
    tags: ["Javascript", "React Js"],
    category: "web app",
    github: "https://github.com/AnirudhPV123/Netflix-react",
  },
];
